"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _program_cards from './program-cards.bones.json'
import _hero_section from './hero-section.bones.json'
import _about_section from './about-section.bones.json'
import _methodology_section from './methodology-section.bones.json'
import _courses_section from './courses-section.bones.json'
import _programs_section from './programs-section.bones.json'
import _contact_section from './contact-section.bones.json'
import _where_we_are_section from './where-we-are-section.bones.json'
import _faq_section from './faq-section.bones.json'
import _app_shell from './app-shell.bones.json'

configureBoneyard({"color":"#E6E6E6","darkColor":"#E6E6E6","animate":"shimmer","shimmerColor":"#E6E6E6","darkShimmerColor":"#E6E6E6","speed":"3s","shimmerAngle":110})

registerBones({
  "program-cards": _program_cards,
  "hero-section": _hero_section,
  "about-section": _about_section,
  "methodology-section": _methodology_section,
  "courses-section": _courses_section,
  "programs-section": _programs_section,
  "contact-section": _contact_section,
  "where-we-are-section": _where_we_are_section,
  "faq-section": _faq_section,
  "app-shell": _app_shell,
})
